[package]
name = "btel"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
regex = "1.11.1"
tree = { git = "https://github.com/Xelezard/rust-tree", version = "0.1.0" }
tui = "0.19.0"
